name: Build Zig Clipboard Manager

on:
  push:
    tags:
      - "zig-app-v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - name: Install X11 dev libraries (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev
      - name: Build
        run: |
          cd zig-app
          zig build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: znip-${{ matrix.os }}
          path: zig-app/main*
